import { Dish, Category, Deal } from './types';

export const categories: Category[] = [
  { id: 'lunch', name: 'Lunch', description: 'Hearty and delicious meals to power your afternoon.' },
  { id: 'desserts', name: 'Desserts', description: 'Sweet treats to end your meal on a high note.' },
  { id: 'drinks', name: 'Drinks', description: 'Refreshing beverages to quench your thirst.' },
];

export const dishes: Dish[] = [
  {
    id: '1',
    name: 'Jollof Rice Supreme',
    description: 'A classic West African dish with smoky rice, fried plantain, and your choice of protein.',
    price: 15.99,
    calories: 650,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/jollof-rice-qg0d03a-1763410529615.webp',
    category: 'Lunch',
    tags: ['Best Seller', 'Spicy'],
    rating: 4.8,
    ingredients: ['Basmati Rice', 'Tomato Stew', 'Chicken', 'Plantain', 'Mixed Vegetables'],
    allergens: ['None'],
  },
  {
    id: '2',
    name: 'Suya Skewers',
    description: 'Spicy grilled beef skewers, coated in a peanut-based spice blend. A Nigerian street food classic.',
    price: 12.50,
    calories: 450,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/suya-skewers-ddvu0y4-1763410537656.webp',
    category: 'Lunch',
    tags: ['Spicy', 'New'],
    rating: 4.7,
    ingredients: ['Beef', 'Yaji Spice', 'Peanuts', 'Onion', 'Bell Pepper'],
    allergens: ['Peanuts'],
  },
  {
    id: '3',
    name: 'Injera Platter (Vegan)',
    description: 'A large, shareable platter of Ethiopian sourdough flatbread served with a variety of savory lentil and vegetable stews.',
    price: 22.00,
    calories: 800,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/injera-platter-e6tlxlx-1763410545545.webp',
    category: 'Lunch',
    tags: ['Vegan', 'Best Seller'],
    rating: 4.9,
    ingredients: ['Teff Flour', 'Red Lentils (Misir Wot)', 'Split Peas (Kik Alicha)', 'Collard Greens (Gomen)', 'Cabbage and Potatoes (Tikil Gomen)'],
    allergens: ['None'],
  },
  {
    id: '4',
    name: 'Durban Bunny Chow',
    description: 'A South African street food classic. A hollowed-out loaf of bread filled with a rich and spicy lamb curry.',
    price: 18.75,
    calories: 950,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/bunny-chow-4rf0v0w-1763410552610.webp',
    category: 'Lunch',
    tags: ['Spicy'],
    rating: 4.6,
    ingredients: ['Lamb Curry', 'White Bread Loaf', 'Potatoes', 'Indian Spices'],
    allergens: ['Gluten'],
  },
  {
    id: '5',
    name: 'Mandazi Delight',
    description: 'Fluffy, slightly sweet East African doughnuts, spiced with cardamom and perfect with a cup of chai.',
    price: 6.50,
    calories: 300,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/mandazi-dessert-ppcdhhx-1763410559662.webp',
    category: 'Desserts',
    tags: [],
    rating: 4.5,
    ingredients: ['Flour', 'Coconut Milk', 'Cardamom', 'Sugar'],
    allergens: ['Gluten'],
  },
  {
    id: '6',
    name: 'Sparkling Chapman',
    description: 'A refreshing non-alcoholic punch, popular in Nigeria. A vibrant mix of fruity flavors.',
    price: 5.00,
    calories: 150,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/chapman-drink-jjzinnk-1763410566703.webp',
    category: 'Drinks',
    tags: [],
    rating: 4.8,
    ingredients: ['Grenadine', 'Orange Soda', 'Lemon-Lime Soda', 'Cucumber', 'Citrus Slices'],
    allergens: ['None'],
  },
    {
    id: '7',
    name: 'Amarula Cheesecake',
    description: 'A creamy, decadent cheesecake infused with the unique flavor of South African Amarula liqueur.',
    price: 8.50,
    calories: 550,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/amarula-cheesecake-tpaowi7-1763410582007.webp',
    category: 'Desserts',
    tags: ['New'],
    rating: 4.9,
    ingredients: ['Cream Cheese', 'Amarula Liqueur', 'Biscuit Base', 'Caramel'],
    allergens: ['Gluten', 'Dairy'],
  }
];

export const deals: Deal[] = [
    {
        id: 'deal-1',
        name: 'Lunch Combo',
        description: 'Jollof Rice + Suya Skewer + Chapman Drink',
        price: 30.00,
        image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/7a324c89-1af0-4263-ac87-5b142101d8e1/combo-deal-0gntxtm-1763410574778.webp',
        discount: 20,
    }
];
